site_name: Move Base Flex Documentation
site_url: https://uos.github.io

repo_name: Github
repo_url: https://github.com/magazino/move_base_flex

docs_dir: docs
theme:
    name: material
    features:
      - navigation.instant
      - navigation.tabs
      - navigation.sections
    logo: img/mbf_icon.png
    favicon: img/mbf_icon.png
    palette:
      primary: cyan

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - admonition
  - attr_list

nav:
  - Home: index.md
  - Showcase: showcase.md
  - Getting Started: 
    - Installation: installation.md
    - Tutorials: tutorials/overview.md
  - Tutorials:
    - Beginner: 
      - Overview: tutorials/beginner/overview.md
      - Basic Navigation: tutorials/beginner/basic_navigation.md
      - Beyond the Relay - Move Base Flex: tutorials/beginner/beyond_relay.md
      - Path Planning: tutorials/beginner/path_planning.md
      - Parameters and Configuration: 
        - Overview: tutorials/beginner/parameters/overview.md
        - MBF Parameters: tutorials/beginner/parameters/mbf_parameters.md
    - Advanced: 
      - Overview: tutorials/advanced/overview.md
      - Writing a simple SMACH: tutorials/advanced/smach.md
      - Continuous Replanning: tutorials/advanced/continuous_replanning.md
      - Recovery Behavior: tutorials/advanced/recovery_behavior.md
      - Behavior Tree (C++): tutorials/advanced/behavior_tree.md
      - Behavior Tree (Python): tutorials/advanced/pytrees.md
    - Expert: 
      - Overview: tutorials/expert/overview.md
      - Multi Robot Navigation: tutorials/expert/multi_robot_navigation.md
      - Multi Planner Navigation: tutorials/expert/multi_planner_navigation.md
      - Custom Recovery Behavior: tutorials/expert/custom_recovery_behavior.md
  - Concepts:
    - Concepts: concepts/concepts.md
